### ISSUE TITLE
I'd like to remap to another combination

### ISSUE THREAD

**Issue by fcojavierdomenech** [xavierchow/vim-sequence-diagram#10]
I'm always getting this when starting vim:

```
Error detected while processing /home/vivo/.vim/plugged/vim-sequence-diagram/plugin/vim-sequence-diagram.vim:
line   16:
E227: mapping already exists for \t
```

I've tried to remap it on the vimrc but it does not solve the issue:

`nmap <unique> <leader>sd <Plug>GenerateDiagram `

**Comment by xavierchow** [comment]
@vivoconunxino sorry for the late response, but I can successfully remap it to other keys, e.g.
```
nmap <unique> <leader>e <Plug>GenerateDiagram
```

could you try to see if your vimrc really takes effect or you can just change the code of plugin directly  as  a workaround.
https://github.com/xavierchow/vim-sequence-diagram/blob/246731d1a01edf196f0f004c7726f3e3560617bf/plugin/vim-sequence-diagram.vim#L16

**Comment by fcojavierdomenech** [comment]
Thanks Xavier,
it's working now, I must have forgotten something before, sorry.
