### ISSUE TITLE
html generated but browser not opened on OS X 10.14.6 

### ISSUE THREAD

**Issue by micheal-w-wells** [xavierchow/vim-sequence-diagram#11]
out.html is generated in /tmp/vim-js-seq but no browser is opened and no error generated, making it seem like nothing is happening.

vim 8

**Comment by xavierchow** [comment]
The browser launching is handled with an AppleScript: https://github.com/xavierchow/vim-sequence-diagram/blob/246731d1a01edf196f0f004c7726f3e3560617bf/autoload/vim_seq_diag.vim#L35-L36.
Can you try to run it directly? @micheal-w-wells

**Comment by micheal-w-wells** [comment]
@xavierchow Thanks for following up!  Here's what I did as requested:

1. Rebooted mac (out.html deleted)
2. Nav'd to /Users/username/.vim/bundle/vim-sequence-diagram/plugin/applescript 
3. Ran directly (opened it in finder and hit 'run').  Got page not found.
4. Opened a .seq file in vim, hit leader t .  No browser opened.
5. Verified that out.html exists again (it did)
6. Ran applescript directly again, this time it rendered the diagram correctly.

**Comment by xavierchow** [comment]
Hmm, this is strange, it does fail if `out.html` doesn't exist. 
This plugin doesn't delete the `out.html`(it always re-generates with `cp` command),
did you remove the html manually or is there any cleanup tool/script on you machine?

**Comment by micheal-w-wells** [comment]
I didn't delete it manually but its gone after a reboot, could be some software my employer put on workstation.  I don't think there's anything preventing applescript though because I can run the script manually.

**Comment by xavierchow** [comment]
Closing, don't feel like a vim plugin issue.
