### ISSUE TITLE
Is it good to have a download button for the generated svg in browser?

### ISSUE THREAD

**Issue by jamesruan** [xavierchow/vim-sequence-diagram#4]
I'm using this for generating diagram for documentation. But it is a tedious work to open developer mode and copy the svg element out and paste it into a svg file manually.

Is it good to have a download button for that, or anything equivalent method that help saving previewed svg?

**Comment by xavierchow** [comment]
Interesting, need to find a proper way to download the svg. Any thoughts?

**Comment by xavierchow** [comment]
Done, you can use the buttons at the bottom to download it as SVG or PNG now.
@jamesruan

**Comment by jamesruan** [comment]
great!

**Comment by xavierchow** [comment]
There's no arrow(SVG marker) in the generated svg or png, reopen to investigate.

**Comment by xavierchow** [comment]
Fixed.
