### ISSUE TITLE
neovim - nothing happens when using map

### ISSUE THREAD

**Issue by jdsutherland** [xavierchow/vim-sequence-diagram#8]
I tried default as well as remapping based on the README but nothing happens when triggering the map that call Generate_diagram.

I tried `:call vim_seq_diag#Generate_diagram("PATH")` and it indeed generates a file in `/tmp/...`. My vim knowledge is lacking in a clear path forward. Any suggestions? There isn't any vim output when the map gets hit so I'm not sure what info I could provide to help here.

**Comment by xavierchow** [comment]
@jdsutherland can you check if there is HTML file generated in the path `/tmp/vim-js-seq/`? 
and what is your OS and browser?

**Comment by xavierchow** [comment]
Or maybe it's just the remap doesn't work for some reason, could you try to use other character with `<leader>` key,
e.g.
`nmap <unique> <leader>e <Plug>GenerateDiagram`

**Comment by jdsutherland** [comment]
I tried several different maps and ensured that the map was actually set using `:map` based on advice at https://vi.stackexchange.com/questions/7722/how-to-debug-a-mapping. It still didn't work. I got it working by hardcoding the path and mapping `:call vim_seq_diag#Generate_diagram()<CR>`. As far as I can tell, there isn't a clear path in further debugging; it seems like it could be many things. I should really learn more about vim and vimscript. Anyways, for sharing the plugin.

**Comment by xavierchow** [comment]
Glad to hear you got it working, it's still weird for me why mapping doesn't work.
FYI, I find my mapping with `:map` command, `n` means normal map, `\` is the `<leader>`, `e` is the character after the `<leader>`.
<img width="405" alt="screenshot 2018-08-03 12 19 47" src="https://user-images.githubusercontent.com/2748884/43624062-9640a6b2-9717-11e8-9b40-a82651ff52ea.png">
